### ISSUE TITLE
the 'crowdstrike_spotlight_vulnerability' table does not work

### ISSUE THREAD

**Issue by marakomer** [turbot/steampipe-plugin-crowdstrike#7]
**Describe the bug**
Any query on the "crowdstrike_spotlight_vulnerability" table returns the following error:

Error: [GET /spotlight/queries/vulnerabilities/v1][403] queryVulnerabilitiesForbidden  &{Errors:[{Code:403 Message:access denied, authorization failed}] Meta:PoweredBy:crowdstrike-api-gateway QueryTime:2.26e-07 TraceID:45a8f4e8-6dcb-43f0-91c5-b27a4b4d3423}} (SQLSTATE HV000)

Despite having all scopes/permissions checked off on the used credentials. The region is us-2.

**Steampipe version**
Example: v0.17.4

**Plugin version**
Example: v0.2.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands):
Run the following Crowstrike steampipe query, the same as the main one in the plugin's page:
```
select
  created_timestamp,
  host_info -> 'hostname' AS hostname,
  status
from
  crowdstrike_spotlight_vulnerability
where
  created_timestamp > now() - interval '15 days';
```

**Expected behavior**
The table should return the required information or be removed from the plugin.

**Comment by bigdatasourav** [comment]
Hey, @marakomer; sorry for the delayed response.

Could you please check and let us know if you have `Spotlight vulnerabilities` under the API scope?
<img width="434" alt="image" src="https://github.com/turbot/steampipe-plugin-crowdstrike/assets/78197905/d45ce3f8-ca2e-400b-aa1e-251bf93769dc">

Falcon Spotlight is a separate product; we need to subscribe to it to access it. https://www.crowdstrike.com/products/security-and-it-operations/falcon-spotlight-vulnerability-management/

**Comment by bigdatasourav** [comment]
Hey @marakomer, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
